AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LFMovieList:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/581918d9ba20f98c1f524efa7b612050
      Handler: movies_list.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-list
            Method: get
      Policies:
      - CloudWatchLogsFullAccess
  LFMovieViews:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/581918d9ba20f98c1f524efa7b612050
      Handler: movies_views.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-watched
            Method: post
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSQSFullAccess
  LFMovieSearch:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/581918d9ba20f98c1f524efa7b612050
      Handler: movies_search.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-search
            Method: get
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonESFullAccess
  LFViewAndRatingUpdater:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: s3://shazam-sam-templates/581918d9ba20f98c1f524efa7b612050
      Handler: view_rating_updater.handler
      Events:
        CloudwatchCronEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSQSFullAccess
  LFEmailSender:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: s3://shazam-sam-templates/581918d9ba20f98c1f524efa7b612050
      Handler: email_sender.handler
      Events:
        CloudwatchCronEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSQSFullAccess
      - AmazonSESFullAccess
  SQSViewsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSViewsQueue
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
