AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LFMovieList:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/d279d5b405a4ae96d80a7df0550816b4
      Handler: movies_list.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-list
            Method: get
      Policies:
      - CloudWatchLogsFullAccess
  LFMovieViews:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/d279d5b405a4ae96d80a7df0550816b4
      Handler: movies_views.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-watched
            Method: post
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSQSFullAccess
  SQSViewsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSViewsQueue
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
