AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LFMovieList:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/ceef048daf0f2eb0f1a646955b0b74de
      Handler: movies_list.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-list
            Method: get
      Policies:
      - CloudWatchLogsFullAccess
