AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LFMovieList:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/76caa6cc1e6593b2a1c439fd65e1615b
      Handler: movies_list.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-list
            Method: get
      Policies:
      - CloudWatchLogsFullAccess
  LFMovieViews:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      CodeUri: s3://shazam-sam-templates/76caa6cc1e6593b2a1c439fd65e1615b
      Handler: movies_views.handler
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /movies-watched
            Method: post
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSQSFullAccess
  LFViewAndRatingUpdater:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: s3://shazam-sam-templates/76caa6cc1e6593b2a1c439fd65e1615b
      Handler: view_rating_updater.handler
      Events:
        CloudwatchCronEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSQSFullAccess
  LFEmailSender:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: s3://shazam-sam-templates/76caa6cc1e6593b2a1c439fd65e1615b
      Handler: email_sender.handler
      Events:
        CloudwatchCronEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
      - CloudWatchLogsFullAccess
      - AmazonSQSFullAccess
      - AmazonSESFullAccess
  SQSViewsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSViewsQueue
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
